#include "cpu.h"
#include "opcodeData.h"
#include "../types.h"
/* Executes non-CB functions. Resets the branched flag before executing the instruction. 
This may be modified by the instruction.  If the instruction involes a conditional jump instruction and 
it was taken, the flag will be set to true. Affects the number of cycles the instruction 
takes to execute and hence the return value of this function.*/
int CPU::executeInstruction(){

//reset the branched flag from last instruction, 
// it will be set to true if the instruction was a branch instruction and was taken.
    jumped = false;
    u8 opcode = mem[pc];
    implementOpcode(opcode);

    if (jumped) return opcodeCyclesJumped[opcode];
    else{
        pc += instructionLengths[opcode];
        return opcodeCycles[opcode];
    }
}

void CPU::implementOpcode(u8 opcode){
    switch(opcode){
        case 0x00: nop(); break;
        case 0x01: ld_r16_n16(BC); break;
        case 0x02: ld_mr16_A(BC); break;
        case 0x03: inc16bit(BC); break;
        case 0x04: inc8bit(B); break;
        case 0x05: dec8bit(B); break;
        case 0x06: ld_r8_n8(B); break;
        case 0x07: rlc_A(); break;
        case 0x08: ld_mn16_SP(); break;
        case 0x09: add_HL_r16(BC); break;
        case 0x0A: ld_r8_mr16(A, BC); break;
        case 0x0B: dec16bit(BC); break;
        case 0x0C: inc8bit(C); break;
        case 0x0D: dec8bit(C); break;
        case 0x0E: ld_r8_n8(C); break;
        case 0x0F: rrc_A(); break;
        case 0x10: stop(); break;
        case 0x11: ld_r16_n16(DE); break;
        case 0x12: ld_mr16_A(DE); break;
        case 0x13: inc16bit(DE); break;
        case 0x14: inc8bit(D); break;
        case 0x15: dec8bit(D); break;
        case 0x16: ld_r8_n8(D); break;
        case 0x17: rl_A(); break;
        case 0x18: jr_n16(); break;
        case 0x19: add_HL_r16(DE); break;
        case 0x1A: ld_r8_mr16(A, DE); break;
        case 0x1B: dec16bit(DE); break;
        case 0x1C: inc8bit(E); break;
        case 0x1D: dec8bit(E); break;
        case 0x1E: ld_r8_n8(E); break;
        case 0x1F: rr_A(); break;
        case 0x20: jr_cc_n16(!Zflag()); break;
        case 0x21: ld_r16_n16(HL); break;
        case 0x22: ld_mHLi_A(); break;
        case 0x23: inc16bit(HL); break;
        case 0x24: inc8bit(H); break;
        case 0x25: dec8bit(H); break;
        case 0x26: ld_r8_n8(H); break;
        case 0x27: daa(); break;
        case 0x28: jr_cc_n16(Zflag()); break;
        case 0x29: add_HL_r16(HL); break;
        case 0x2A: ld_A_mHLi(); break;
        case 0x2B: dec16bit(HL); break;
        case 0x2C: inc8bit(L); break;
        case 0x2D: dec8bit(L); break;
        case 0x2E: ld_r8_n8(L); break;
        case 0x2F: cpl(); break;
        case 0x30: jr_cc_n16(!Cflag()); break;
        case 0x31: ld_SP_n16(); break;
        case 0x32: ld_mHLd_A(); break;
        case 0x33: inc16bit(sp); break;
        case 0x34: inc8bit(mem[HL]); break;
        case 0x35: dec8bit(mem[HL]); break;
        case 0x36: ld_mr16_n8(HL); break;
        case 0x37: scf(); break;
        case 0x38: jr_cc_n16(Cflag()); break;
        case 0x39: add_HL_SP(); break;
        case 0x3A: ld_A_mHLd(); break;
        case 0x3B: dec16bit(sp); break;
        case 0x3C: inc8bit(A); break;
        case 0x3D: dec8bit(A); break;
        case 0x3E: ld_r8_n8(A); break;
        case 0x3F: ccf(); break;
        case 0x40: ld_r8_r8(B, B); break;
        case 0x41: ld_r8_r8(B, C); break;
        case 0x42: ld_r8_r8(B, D); break;
        case 0x43: ld_r8_r8(B, E); break;
        case 0x44: ld_r8_r8(B, H); break;
        case 0x45: ld_r8_r8(B, L); break;
        case 0x46: ld_r8_mr16(B, HL); break;
        case 0x47: ld_r8_r8(B, A); break;
        case 0x48: ld_r8_r8(C, B); break;
        case 0x49: ld_r8_r8(C, C); break;
        case 0x4A: ld_r8_r8(C, D); break;
        case 0x4B: ld_r8_r8(C, E); break;
        case 0x4C: ld_r8_r8(C, H); break;
        case 0x4D: ld_r8_r8(C, L); break;
        case 0x4E: ld_r8_mr16(C, HL); break;
        case 0x4F: ld_r8_r8(C, A); break;
        case 0x50: ld_r8_r8(D, B); break;
        case 0x51: ld_r8_r8(D, C); break;
        case 0x52: ld_r8_r8(D, D); break;
        case 0x53: ld_r8_r8(D, E); break;
        case 0x54: ld_r8_r8(D, H); break;
        case 0x55: ld_r8_r8(D, L); break;
        case 0x56: ld_r8_mr16(D, HL); break;
        case 0x57: ld_r8_r8(D, A); break;
        case 0x58: ld_r8_r8(E, B); break;
        case 0x59: ld_r8_r8(E, C); break;
        case 0x5A: ld_r8_r8(E, D); break;
        case 0x5B: ld_r8_r8(E, E); break;
        case 0x5C: ld_r8_r8(E, H); break;
        case 0x5D: ld_r8_r8(E, L); break;
        case 0x5E: ld_r8_mr16(E, HL); break;
        case 0x5F: ld_r8_r8(E, A); break;
        case 0x60: ld_r8_r8(H, B); break;
        case 0x61: ld_r8_r8(H, C); break;
        case 0x62: ld_r8_r8(H, D); break;
        case 0x63: ld_r8_r8(H, E); break;
        case 0x64: ld_r8_r8(H, H); break;
        case 0x65: ld_r8_r8(H, L); break;
        case 0x66: ld_r8_mr16(H, HL); break;
        case 0x67: ld_r8_r8(H, A); break;
        case 0x68: ld_r8_r8(L, B); break;
        case 0x69: ld_r8_r8(L, C); break;
        case 0x6A: ld_r8_r8(L, D); break;
        case 0x6B: ld_r8_r8(L, E); break;
        case 0x6C: ld_r8_r8(L, H); break;
        case 0x6D: ld_r8_r8(L, L); break;
        case 0x6E: ld_r8_mr16(L, HL); break;
        case 0x6F: ld_r8_r8(L, A); break;
        case 0x70: ld_mr16_r8(HL, B); break;
        case 0x71: ld_mr16_r8(HL, C); break;
        case 0x72: ld_mr16_r8(HL, D); break;
        case 0x73: ld_mr16_r8(HL, E); break;
        case 0x74: ld_mr16_r8(HL, H); break;
        case 0x75: ld_mr16_r8(HL, L); break;
        case 0x76: halt(); break;
        case 0x77: ld_mr16_r8(HL, A); break;
        case 0x78: ld_r8_r8(A, B); break;
        case 0x79: ld_r8_r8(A, C); break;
        case 0x7A: ld_r8_r8(A, D); break;
        case 0x7B: ld_r8_r8(A, E); break;
        case 0x7C: ld_r8_r8(A, H); break;
        case 0x7D: ld_r8_r8(A, L); break;
        case 0x7E: ld_r8_mr16(A, HL); break;
        case 0x7F: ld_r8_r8(A, A); break;
        case 0x80: add_A_r8(B); break;
        case 0x81: add_A_r8(C); break;
        case 0x82: add_A_r8(D); break;
        case 0x83: add_A_r8(E); break;
        case 0x84: add_A_r8(H); break;
        case 0x85: add_A_r8(L); break;
        case 0x86: add_A_mHL(); break;
        case 0x87: add_A_r8(A); break;
        case 0x88: adc_A_r8(B); break;
        case 0x89: adc_A_r8(C); break;
        case 0x8A: adc_A_r8(D); break;
        case 0x8B: adc_A_r8(E); break;
        case 0x8C: adc_A_r8(H); break;
        case 0x8D: adc_A_r8(L); break;
        case 0x8E: adc_A_mHL(); break;
        case 0x8F: adc_A_r8(A); break;
        case 0x90: sub_A(B); break;
        case 0x91: sub_A(C); break;
        case 0x92: sub_A(D); break;
        case 0x93: sub_A(E); break;
        case 0x94: sub_A(H); break;
        case 0x95: sub_A(L); break;
        case 0x96: sub_A(mem[HL]); break;
        case 0x97: sub_A(A); break;
        case 0x98: sbc_A(B); break;
        case 0x99: sbc_A(C); break;
        case 0x9A: sbc_A(D); break;
        case 0x9B: sbc_A(E); break;
        case 0x9C: sbc_A(H); break;
        case 0x9D: sbc_A(L); break;
        case 0x9E: sbc_A(mem[HL]); break;
        case 0x9F: sbc_A(A); break;
        case 0xA0: and_A(B); break;
        case 0xA1: and_A(C); break;
        case 0xA2: and_A(D); break;
        case 0xA3: and_A(E); break;
        case 0xA4: and_A(H); break;
        case 0xA5: and_A(L); break;
        case 0xA6: and_A(mem[HL]); break;
        case 0xA7: and_A(A); break;
        case 0xA8: xor_A(B); break;
        case 0xA9: xor_A(C); break;
        case 0xAA: xor_A(D); break;
        case 0xAB: xor_A(E); break;
        case 0xAC: xor_A(H); break;
        case 0xAD: xor_A(L); break;
        case 0xAE: xor_A(mem[HL]); break;
        case 0xAF: xor_A(A); break;
        case 0xB0: or_A(B); break;
        case 0xB1: or_A(C); break;
        case 0xB2: or_A(D); break;
        case 0xB3: or_A(E); break;
        case 0xB4: or_A(H); break;
        case 0xB5: or_A(L); break;
        case 0xB6: or_A(mem[HL]); break;
        case 0xB7: or_A(A); break;
        case 0xB8: cp_A(B); break;
        case 0xB9: cp_A(C); break;
        case 0xBA: cp_A(D); break;
        case 0xBB: cp_A(E); break;
        case 0xBC: cp_A(H); break;
        case 0xBD: cp_A(L); break;
        case 0xBE: cp_A(mem[HL]); break;
        case 0xBF: cp_A(A); break;
        case 0xC0: ret_cc(!Zflag()); break;
        case 0xC1: pop_r16(BC); break;
        case 0xC2: jp_cc_n16(!Zflag()); break;
        case 0xC3: jp_n16(); break;
        case 0xC4: call_cc_n16(!Zflag()); break;
        case 0xC5: push_r16(BC); break;
        case 0xC6: add_A_n8(); break;
        case 0xC7: rst(0x00); break;
        case 0xC8: ret_cc(Zflag()); break;
        case 0xC9: ret(); break;
        case 0xCA: jp_cc_n16(Zflag()); break;
        case 0xCB: implementCBOpcode(); break;
        case 0xCC: call_cc_n16(Zflag()); break;
        case 0xCD: call_n16(); break;
        case 0xCE: adc_A_n8(); break;
        case 0xCF: rst(0x08); break;
        case 0xD0: ret_cc(!Cflag()); break;
        case 0xD1: pop_r16(DE); break;
        case 0xD2: jp_cc_n16(!Cflag()); break;
        case 0xD3: break; // Unimplemented opcode
        case 0xD4: call_cc_n16(!Cflag()); break;
        case 0xD5: push_r16(DE); break;
        case 0xD6: sub_A(mem[pc+1]); break;
        case 0xD7: rst(0x10); break;
        case 0xD8: ret_cc(Cflag()); break;
        case 0xD9: reti(); break;
        case 0xDA: jp_cc_n16(Cflag()); break;
        case 0xDB: break; // Unimplemented opcode
        case 0xDC: call_cc_n16(Cflag()); break;
        case 0xDD: break; // Unimplemented opcode
        case 0xDE: sbc_A(mem[pc+1]); break;
        case 0xDF: rst(0x18); break;
        case 0xE0: ldh_mn16_A(); break;
        case 0xE1: pop_r16(HL); break;
        case 0xE2: ldh_mC_A(); break;
        case 0xE3: break; // Unimplemented opcode
        case 0xE4: break; // Unimplemented opcode
        case 0xE5: push_r16(HL); break;
        case 0xE6: and_A(mem[pc+1]); break;
        case 0xE7: rst(0x20); break;
        case 0xE8: add_SP_e8(); break;
        case 0xE9: jp_HL(); break;
        case 0xEA: ld_mn16_A(); break;
        case 0xEB: break; // Unimplemented opcode
        case 0xEC: break; // Unimplemented opcode
        case 0xED: break; // Unimplemented opcode
        case 0xEE: xor_A(mem[pc+1]); break;
        case 0xEF: rst(0x28); break;
        case 0xF0: ldh_A_mn16(); break;
        case 0xF1: pop_AF(); break;
        case 0xF2: ldh_A_mC(); break;
        case 0xF3: di(); break;
        case 0xF4: break; // Unimplemented opcode
        case 0xF5: push_r16(AF); break;
        case 0xF6: or_A(mem[pc+1]); break;
        case 0xF7: rst(0x30); break;
        case 0xF8: ld_HL_SPe8(); break;
        case 0xF9: ld_SP_HL(); break;
        case 0xFA: ld_A_mn16(); break;
        case 0xFB: ei(); break;
        case 0xFC: break; // Unimplemented opcode
        case 0xFD: break; // Unimplemented opcode
        case 0xFE: cp_A(mem[pc+1]); break;
        case 0xFF: rst(0x38); break;
    }
}

void CPU::implementCBOpcode(){
    u8 opcode = mem[pc+1];

    switch(opcode){
        case 0x00: rlc_r8(B); break;
        case 0x01: rlc_r8(C); break;
        case 0x02: rlc_r8(D); break;
        case 0x03: rlc_r8(E); break;
        case 0x04: rlc_r8(H); break;
        case 0x05: rlc_r8(L); break;
        case 0x06: rlc_mHL(); break;
        case 0x07: rlc_A(); break;
        case 0x08: rrc_r8(B); break;
        case 0x09: rrc_r8(C); break;
        case 0x0A: rrc_r8(D); break;
        case 0x0B: rrc_r8(E); break;
        case 0x0C: rrc_r8(H); break;
        case 0x0D: rrc_r8(L); break;
        case 0x0E: rrc_mHL(); break;
        case 0x0F: rrc_A(); break;
        case 0x10: rl_r8(B); break;
        case 0x11: rl_r8(C); break;
        case 0x12: rl_r8(D); break;
        case 0x13: rl_r8(E); break;
        case 0x14: rl_r8(H); break;
        case 0x15: rl_r8(L); break;
        case 0x16: rl_mHL(); break;
        case 0x17: rl_A(); break;
        case 0x18: rr_r8(B); break;
        case 0x19: rr_r8(C); break;
        case 0x1A: rr_r8(D); break;
        case 0x1B: rr_r8(E); break;
        case 0x1C: rr_r8(H); break;
        case 0x1D: rr_r8(L); break;
        case 0x1E: rr_mHL(); break;
        case 0x1F: rr_A(); break;
        case 0x20: sla_r8(B); break;
        case 0x21: sla_r8(C); break;
        case 0x22: sla_r8(D); break;
        case 0x23: sla_r8(E); break;
        case 0x24: sla_r8(H); break;
        case 0x25: sla_r8(L); break;
        case 0x26: sla_mHL(); break;
        case 0x27: sla_r8(A); break;
        case 0x28: sra_r8(B); break;
        case 0x29: sra_r8(C); break;
        case 0x2A: sra_r8(D); break;
        case 0x2B: sra_r8(E); break;
        case 0x2C: sra_r8(H); break;
        case 0x2D: sra_r8(L); break;
        case 0x2E: sra_mHL(); break;
        case 0x2F: sra_r8(A); break;
        case 0x30: swap_r8(B); break;
        case 0x31: swap_r8(C); break;
        case 0x32: swap_r8(D); break;
        case 0x33: swap_r8(E); break;
        case 0x34: swap_r8(H); break;
        case 0x35: swap_r8(L); break;
        case 0x36: swap_mHL(); break;
        case 0x37: swap_r8(A); break;
        case 0x38: srl_r8(B); break;
        case 0x39: srl_r8(C); break;
        case 0x3A: srl_r8(D); break;
        case 0x3B: srl_r8(E); break;
        case 0x3C: srl_r8(H); break;
        case 0x3D: srl_r8(L); break;
        case 0x3E: srl_mHL(); break;
        case 0x3F: srl_r8(A); break;
        case 0x40: bit_u3_r8(0, B); break;
        case 0x41: bit_u3_r8(0, C); break;
        case 0x42: bit_u3_r8(0, D); break;
        case 0x43: bit_u3_r8(0, E); break;
        case 0x44: bit_u3_r8(0, H); break;
        case 0x45: bit_u3_r8(0, L); break;
        case 0x46: bit_u3_mHL(0); break;
        case 0x47: bit_u3_r8(0, A); break;
        case 0x48: bit_u3_r8(1, B); break;
        case 0x49: bit_u3_r8(1, C); break;
        case 0x4A: bit_u3_r8(1, D); break;
        case 0x4B: bit_u3_r8(1, E); break;
        case 0x4C: bit_u3_r8(1, H); break;
        case 0x4D: bit_u3_r8(1, L); break;
        case 0x4E: bit_u3_mHL(1); break;
        case 0x4F: bit_u3_r8(1, A); break;
        case 0x50: bit_u3_r8(2, B); break;
        case 0x51: bit_u3_r8(2, C); break;
        case 0x52: bit_u3_r8(2, D); break;
        case 0x53: bit_u3_r8(2, E); break;
        case 0x54: bit_u3_r8(2, H); break;
        case 0x55: bit_u3_r8(2, L); break;
        case 0x56: bit_u3_mHL(2); break;
        case 0x57: bit_u3_r8(2, A); break;
        case 0x58: bit_u3_r8(3, B); break;
        case 0x59: bit_u3_r8(3, C); break;
        case 0x5A: bit_u3_r8(3, D); break;
        case 0x5B: bit_u3_r8(3, E); break;
        case 0x5C: bit_u3_r8(3, H); break;
        case 0x5D: bit_u3_r8(3, L); break;
        case 0x5E: bit_u3_mHL(3); break;
        case 0x5F: bit_u3_r8(3, A); break;
        case 0x60: res_u3_r8(4, B); break;
        case 0x61: res_u3_r8(4, C); break;
        case 0x62: res_u3_r8(4, D); break;
        case 0x63: res_u3_r8(4, E); break;
        case 0x64: res_u3_r8(4, H); break;
        case 0x65: res_u3_r8(4, L); break;
        case 0x66: res_u3_mHL(4); break;
        case 0x67: res_u3_r8(4, A); break;
        case 0x68: res_u3_r8(5, B); break;
        case 0x69: res_u3_r8(5, C); break;
        case 0x6A: res_u3_r8(5, D); break;
        case 0x6B: res_u3_r8(5, E); break;
        case 0x6C: res_u3_r8(5, H); break;
        case 0x6D: res_u3_r8(5, L); break;
        case 0x6E: res_u3_mHL(5); break;
        case 0x6F: res_u3_r8(5, A); break;
        case 0x70: res_u3_r8(6, B); break;
        case 0x71: res_u3_r8(6, C); break;
        case 0x72: res_u3_r8(6, D); break;
        case 0x73: res_u3_r8(6, E); break;
        case 0x74: res_u3_r8(6, H); break;
        case 0x75: res_u3_r8(6, L); break;
        case 0x76: res_u3_mHL(6); break;
        case 0x77: res_u3_r8(6, A); break;
        case 0x78: res_u3_r8(7, B); break;
        case 0x79: res_u3_r8(7, C); break;
        case 0x7A: res_u3_r8(7, D); break;
        case 0x7B: res_u3_r8(7, E); break;
        case 0x7C: res_u3_r8(7, H); break;
        case 0x7D: res_u3_r8(7, L); break;
        case 0x7E: res_u3_mHL(7); break;
        case 0x7F: res_u3_r8(7, A); break;
        case 0x80: res_u3_r8(0, B); break;
        case 0x81: res_u3_r8(0, C); break;
        case 0x82: res_u3_r8(0, D); break;
        case 0x83: res_u3_r8(0, E); break;
        case 0x84: res_u3_r8(0, H); break;
        case 0x85: res_u3_r8(0, L); break;
        case 0x86: res_u3_mHL(0); break;
        case 0x87: res_u3_r8(0, A); break;
        case 0x88: res_u3_r8(1, B); break;
        case 0x89: res_u3_r8(1, C); break;
        case 0x8A: res_u3_r8(1, D); break;
        case 0x8B: res_u3_r8(1, E); break;
        case 0x8C: res_u3_r8(1, H); break;
        case 0x8D: res_u3_r8(1, L); break;
        case 0x8E: res_u3_mHL(1); break;
        case 0x8F: res_u3_r8(1, A); break;
        case 0x90: res_u3_r8(2, B); break;
        case 0x91: res_u3_r8(2, C); break;
        case 0x92: res_u3_r8(2, D); break;
        case 0x93: res_u3_r8(2, E); break;
        case 0x94: res_u3_r8(2, H); break;
        case 0x95: res_u3_r8(2, L); break;
        case 0x96: res_u3_mHL(2); break;
        case 0x97: res_u3_r8(2, A); break;
        case 0x98: res_u3_r8(3, B); break;
        case 0x99: res_u3_r8(3, C); break;
        case 0x9A: res_u3_r8(3, D); break;
        case 0x9B: res_u3_r8(3, E); break;
        case 0x9C: res_u3_r8(3, H); break;
        case 0x9D: res_u3_r8(3, L); break;
        case 0x9E: res_u3_mHL(3); break;
        case 0x9F: res_u3_r8(3, A); break;
        case 0xA0: set_u3_r8(4, B); break;
        case 0xA1: set_u3_r8(4, C); break;
        case 0xA2: set_u3_r8(4, D); break;
        case 0xA3: set_u3_r8(4, E); break;
        case 0xA4: set_u3_r8(4, H); break;
        case 0xA5: set_u3_r8(4, L); break;
        case 0xA6: set_u3_mHL(4); break;
        case 0xA7: set_u3_r8(4, A); break;
        case 0xA8: set_u3_r8(5, B); break;
        case 0xA9: set_u3_r8(5, C); break;
        case 0xAA: set_u3_r8(5, D); break;
        case 0xAB: set_u3_r8(5, E); break;
        case 0xAC: set_u3_r8(5, H); break;
        case 0xAD: set_u3_r8(5, L); break;
        case 0xAE: set_u3_mHL(5); break;
        case 0xAF: set_u3_r8(5, A); break;
        case 0xB0: set_u3_r8(6, B); break;
        case 0xB1: set_u3_r8(6, C); break;
        case 0xB2: set_u3_r8(6, D); break;
        case 0xB3: set_u3_r8(6, E); break;
        case 0xB4: set_u3_r8(6, H); break;
        case 0xB5: set_u3_r8(6, L); break;
        case 0xB6: set_u3_mHL(6); break;
        case 0xB7: set_u3_r8(6, A); break;
        case 0xB8: set_u3_r8(7, B); break;
        case 0xB9: set_u3_r8(7, C); break;
        case 0xBA: set_u3_r8(7, D); break;
        case 0xBB: set_u3_r8(7, E); break;
        case 0xBC: set_u3_r8(7, H); break;
        case 0xBD: set_u3_r8(7, L); break;
        case 0xBE: set_u3_mHL(7); break;
        case 0xBF: set_u3_r8(7, A); break;
        case 0xC0: set_u3_r8(0, B); break;
        case 0xC1: set_u3_r8(0, C); break;
        case 0xC2: set_u3_r8(0, D); break;
        case 0xC3: set_u3_r8(0, E); break;
        case 0xC4: set_u3_r8(0, H); break;
        case 0xC5: set_u3_r8(0, L); break;
        case 0xC6: set_u3_mHL(0); break;
        case 0xC7: set_u3_r8(0, A); break;
        case 0xC8: set_u3_r8(1, B); break;
        case 0xC9: set_u3_r8(1, C); break;
        case 0xCA: set_u3_r8(1, D); break;
        case 0xCB: set_u3_r8(1, E); break;
        case 0xCC: set_u3_r8(1, H); break;
        case 0xCD: set_u3_r8(1, L); break;
        case 0xCE: set_u3_mHL(1); break;
        case 0xCF: set_u3_r8(1, A); break;
        case 0xD0: set_u3_r8(2, B); break;
        case 0xD1: set_u3_r8(2, C); break;
        case 0xD2: set_u3_r8(2, D); break;
        case 0xD3: set_u3_r8(2, E); break;
        case 0xD4: set_u3_r8(2, H); break;
        case 0xD5: set_u3_r8(2, L); break;
        case 0xD6: set_u3_mHL(2); break;
        case 0xD7: set_u3_r8(2, A); break;
        case 0xD8: set_u3_r8(3, B); break;
        case 0xD9: set_u3_r8(3, C); break;
        case 0xDA: set_u3_r8(3, D); break;
        case 0xDB: set_u3_r8(3, E); break;
        case 0xDC: set_u3_r8(3, H); break;
        case 0xDD: set_u3_r8(3, L); break;
        case 0xDE: set_u3_mHL(3); break;
        case 0xDF: set_u3_r8(3, A); break;
        case 0xE0: set_u3_r8(4, B); break;
        case 0xE1: set_u3_r8(4, C); break;
        case 0xE2: set_u3_r8(4, D); break;
        case 0xE3: set_u3_r8(4, E); break;
        case 0xE4: set_u3_r8(4, H); break;
        case 0xE5: set_u3_r8(4, L); break;
        case 0xE6: set_u3_mHL(4); break;
        case 0xE7: set_u3_r8(4, A); break;
        case 0xE8: set_u3_r8(5, B); break;
        case 0xE9: set_u3_r8(5, C); break;
        case 0xEA: set_u3_r8(5, D); break;
        case 0xEB: set_u3_r8(5, E); break;
        case 0xEC: set_u3_r8(5, H); break;
        case 0xED: set_u3_r8(5, L); break;
        case 0xEE: set_u3_mHL(5); break;
        case 0xEF: set_u3_r8(5, A); break;
        case 0xF0: set_u3_r8(6, B); break;
        case 0xF1: set_u3_r8(6, C); break;
        case 0xF2: set_u3_r8(6, D); break;
        case 0xF3: set_u3_r8(6, E); break;
        case 0xF4: set_u3_r8(6, H); break;
        case 0xF5: set_u3_r8(6, L); break;
        case 0xF6: set_u3_mHL(6); break;
        case 0xF7: set_u3_r8(6, A); break;
        case 0xF8: set_u3_r8(7, B); break;
        case 0xF9: set_u3_r8(7, C); break;
        case 0xFA: set_u3_r8(7, D); break;
        case 0xFB: set_u3_r8(7, E); break;
        case 0xFC: set_u3_r8(7, H); break;
        case 0xFD: set_u3_r8(7, L); break;
        case 0xFE: set_u3_mHL(7); break;
        case 0xFF: set_u3_r8(7, A); break;
    }
    
}
